### ISSUE TITLE
Wont work with V3.0 or JetPack 4.4

### ISSUE THREAD

**Issue by GuiSteffen** [TrojanXu/yolov5-tensorrt#37]
The code is not yet available to work on Jetpack 4.4.

The current version requires PYTorch 1.4.0 to be installed, altough the Jetpack 4.4 production dont support Pytorch < 1.6.0.

Anybody using Jetpack 4.4 are currently in a loop hole. Follows the error (PyTorch Incompatibility)

Does anybody has a solution to this? Will we have an implementation of TRT for Pytorch 1.6?

`torch.nn.modules.module.ModuleAttributeError: 'BatchNorm2d' object has no attribute '_non_persistent_buffers_set'
`

**Comment by TrojanXu** [comment]
Updated with tag v3.0
